services:
  go-average-price:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBIAN_VERSION: bookworm
    volumes:
      - ..:/go-average-price:cached
    command: sleep infinity
    user: vscode
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      - default

networks:
  default:
    driver: bridge
